import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { CostosService } from '../../core/services/costos/costos.service';

@Component({selector:'app-costos-certificaciones',standalone:true,imports:[CommonModule,FormsModule,RouterLink,MatIconModule],templateUrl:'./costos-certificaciones.html',styleUrls:['./costos-certificaciones.css','./costos-certificaciones.cards.css','./costos-certificaciones.finanzas.css','./costos-certificaciones.resizable.css','./costos-certificaciones.dashboard.css']})
export class CostosCertificaciones implements OnInit{
  readonly titulosColumnas=['SEC.','ETAPA / OPERACIÓN','RESPONSABLE','AVANCE CLIENTE','AVANCE RESPONSABLE','PRECIO CLIENTE','COSTO RESPONSABLE','CRONOGRAMA CERT. CLIENTE','N° CERT. CLIENTE','CRONOGRAMA CERT. RESPONSABLE','N° CERT. RESPONSABLE','ESTADO',''];
  anchosColumnas=[100,520,360,180,200,190,210,230,180,260,210,180,90];
  private redimensionandoColumna:{indice:number;inicioX:number;anchoInicial:number;pointerId:number}|null=null;
  readonly titulosColumnasImportacion=['FILA','SEC.','ETAPA / OPERACIÓN','PRECIO ANTERIOR','PRECIO NUEVO','COSTO ANTERIOR','COSTO NUEVO','CRONOGRAMA CLIENTE','N° CERT. CLIENTE','CRONOGRAMA RESPONSABLE','N° CERT. RESPONSABLE','VALIDACIÓN'];
  anchosColumnasImportacion=[60,80,320,150,150,150,150,220,180,240,200,220];
  private redimensionandoColumnaImportacion:{indice:number;inicioX:number;anchoInicial:number;pointerId:number}|null=null;
  etapasColapsadas=new Set<number>();
  proyectoId=0;proyecto:any;operaciones:any[]=[];etapasOperaciones:any[]=[];certificados:any[]=[];certificadosResponsable:any[]=[];responsables:any[]=[];tab:'economia'|'dashboard'|'preview'|'historial'|'responsable_preview'|'responsable_historial'|'movimientos'='economia';cargando=true;procesando=false;error='';mensaje='';
  editando:any=null;motivo='';historialEconomia:any[]=[];fecha=this.hoyLocal();previewData:any=null;observaciones='';detalle:any=null;permisos=new Set<string>();
  metodoCorte:'POR_FECHA'|'POR_OPERACION'='POR_FECHA';operacionCorteId:number|null=null;
  importacion:any=null;contenidoCsv='';nombreArchivo='';
  eliminandoCertificado:any=null;motivoEliminacion='';
  responsableId:number|null=null;metodoCorteResponsable:'POR_FECHA'|'POR_OPERACION'='POR_FECHA';operacionCorteResponsableId:number|null=null;fechaResponsable=this.hoyLocal();previewResponsableData:any=null;observacionesResponsable='';detalleResponsable:any=null;eliminandoCertificadoResponsable:any=null;motivoEliminacionResponsable='';
  finanzas:any=null;mostrandoMovimiento=false;nuevoMovimiento:any=this.movimientoVacio();anulandoMovimiento:any=null;motivoAnulacionMovimiento='';errorModal='';
  dashboardData:any=null;cargandoDashboard=false;
  private certificadosCargados=false;
  private certificadosResponsableCargados=false;
  private movimientosCargados=false;
  private dashboardCargado=false;
  constructor(private route:ActivatedRoute,private api:CostosService){}
  ngOnInit(){this.cargarAnchosColumnas();this.cargarAnchosColumnasImportacion();this.proyectoId=Number(this.route.snapshot.paramMap.get('id'));this.api.permisos().subscribe({next:p=>{this.permisos=new Set(p);this.cargar();},error:e=>this.fallar(e,'No se pudieron validar los permisos')});}
  anchoTotalColumnas(){return this.anchosColumnas.reduce((total,ancho)=>total+ancho,0);}
  iniciarRedimensionColumna(event:PointerEvent,indice:number){event.preventDefault();event.stopPropagation();const objetivo=event.currentTarget as HTMLElement;objetivo.setPointerCapture(event.pointerId);this.redimensionandoColumna={indice,inicioX:event.clientX,anchoInicial:this.anchosColumnas[indice],pointerId:event.pointerId};}
  redimensionarColumna(event:PointerEvent){const estado=this.redimensionandoColumna;if(!estado||estado.pointerId!==event.pointerId)return;const minimo=estado.indice===this.anchosColumnas.length-1?52:72;this.anchosColumnas[estado.indice]=Math.max(minimo,estado.anchoInicial+event.clientX-estado.inicioX);this.anchosColumnas=[...this.anchosColumnas];}
  finalizarRedimensionColumna(event:PointerEvent){const estado=this.redimensionandoColumna;if(!estado||estado.pointerId!==event.pointerId)return;const objetivo=event.currentTarget as HTMLElement;if(objetivo.hasPointerCapture(event.pointerId))objetivo.releasePointerCapture(event.pointerId);this.redimensionandoColumna=null;try{localStorage.setItem('costos-operaciones-anchos-columnas-v3',JSON.stringify(this.anchosColumnas));}catch{}}
  private cargarAnchosColumnas(){try{const guardados=JSON.parse(localStorage.getItem('costos-operaciones-anchos-columnas-v3')||'null');if(Array.isArray(guardados)&&guardados.length===this.anchosColumnas.length&&guardados.every((ancho:any)=>Number.isFinite(Number(ancho))&&Number(ancho)>=52))this.anchosColumnas=guardados.map(Number);}catch{}}
  anchoTotalColumnasImportacion(){return this.anchosColumnasImportacion.reduce((total,ancho)=>total+ancho,0);}
  iniciarRedimensionColumnaImportacion(event:PointerEvent,indice:number){event.preventDefault();event.stopPropagation();const objetivo=event.currentTarget as HTMLElement;objetivo.setPointerCapture(event.pointerId);this.redimensionandoColumnaImportacion={indice,inicioX:event.clientX,anchoInicial:this.anchosColumnasImportacion[indice],pointerId:event.pointerId};}
  redimensionarColumnaImportacion(event:PointerEvent){const estado=this.redimensionandoColumnaImportacion;if(!estado||estado.pointerId!==event.pointerId)return;this.anchosColumnasImportacion[estado.indice]=Math.max(52,estado.anchoInicial+event.clientX-estado.inicioX);this.anchosColumnasImportacion=[...this.anchosColumnasImportacion];}
  finalizarRedimensionColumnaImportacion(event:PointerEvent){const estado=this.redimensionandoColumnaImportacion;if(!estado||estado.pointerId!==event.pointerId)return;const objetivo=event.currentTarget as HTMLElement;if(objetivo.hasPointerCapture(event.pointerId))objetivo.releasePointerCapture(event.pointerId);this.redimensionandoColumnaImportacion=null;try{localStorage.setItem('costos-importacion-anchos-columnas-v2',JSON.stringify(this.anchosColumnasImportacion));}catch{}}
  private cargarAnchosColumnasImportacion(){try{const guardados=JSON.parse(localStorage.getItem('costos-importacion-anchos-columnas-v2')||'null');if(Array.isArray(guardados)&&guardados.length===this.anchosColumnasImportacion.length&&guardados.every((ancho:any)=>Number.isFinite(Number(ancho))&&Number(ancho)>=52))this.anchosColumnasImportacion=guardados.map(Number);}catch{}}
  puede(codigo:string){return this.permisos.has(codigo);}
  etapaColapsada(etapaId:number){return this.etapasColapsadas.has(Number(etapaId));}
  alternarEtapa(etapaId:number){const id=Number(etapaId);const nuevas=new Set(this.etapasColapsadas);if(nuevas.has(id))nuevas.delete(id);else nuevas.add(id);this.etapasColapsadas=nuevas;}
  hoyLocal(){const hoy=new Date();return `${hoy.getFullYear()}-${String(hoy.getMonth()+1).padStart(2,'0')}-${String(hoy.getDate()).padStart(2,'0')}`;}
  fechaCalendario(valor:any){const iso=String(valor||'').slice(0,10),partes=iso.split('-');return partes.length===3?`${partes[2]}/${partes[1]}/${partes[0]}`:'-';}
  cargar(){this.cargando=true;this.error='';this.api.economia(this.proyectoId).subscribe({next:r=>{this.proyecto=r.proyecto;this.operaciones=r.operaciones;this.etapasOperaciones=this.agruparOperaciones(r.operaciones);const mapa=new Map<number,any>();for(const op of this.operaciones)if(op.responsable_id&&!mapa.has(Number(op.responsable_id)))mapa.set(Number(op.responsable_id),{responsable_id:Number(op.responsable_id),nombre:op.responsable_nombre,operaciones:this.operaciones.filter((x:any)=>Number(x.responsable_id)===Number(op.responsable_id))});this.responsables=[...mapa.values()].sort((a,b)=>String(a.nombre).localeCompare(String(b.nombre)));this.cargando=false;},error:e=>this.fallar(e,'No se pudo cargar el modulo')});}
  agruparOperaciones(operaciones:any[]){const grupos=new Map<number,any>();for(const op of operaciones||[]){const id=Number(op.etapa_id);if(!grupos.has(id))grupos.set(id,{etapa_id:id,codigo:String(op.etapa_codigo||`E${Number(op.etapa_orden)||grupos.size+1}`).toUpperCase(),nombre:op.etapa_nombre,orden:Number(op.etapa_orden||0),peso_pct:Number(op.etapa_peso_pct||0),costo_total:0,avance_etapa:0,avance_certificado:0,operaciones:[]});const grupo=grupos.get(id),peso=Number(op.peso_operacion||0);grupo.operaciones.push(op);grupo.costo_total+=Number(op.costo_responsable||0);grupo.avance_etapa+=Number(op.pct_avance_actual||0)*peso/100;grupo.avance_certificado+=Number(op.pct_certificado_actual||0)*peso/100;}return[...grupos.values()].map(g=>({...g,costo_total:Number(g.costo_total.toFixed(4)),avance_etapa:Number(g.avance_etapa.toFixed(3)),avance_certificado:Number(g.avance_certificado.toFixed(3))})).sort((a,b)=>a.orden-b.orden);}
  cargarCertificados(forzar=false){if(this.certificadosCargados&&!forzar)return;this.api.certificados(this.proyectoId).subscribe({next:r=>{this.certificados=r;this.certificadosCargados=true;},error:e=>this.error=e?.error?.message||'No se pudieron cargar los certificados'});}
  cargarCertificadosResponsable(forzar=false){if(this.certificadosResponsableCargados&&!forzar)return;this.api.certificadosResponsable(this.proyectoId).subscribe({next:r=>{this.certificadosResponsable=r;this.certificadosResponsableCargados=true;},error:e=>this.error=e?.error?.message||'No se pudieron cargar los certificados a responsables'});}
  cambiarTab(tab:any){this.tab=tab;this.error='';this.mensaje='';if(tab==='dashboard')this.cargarDashboard();if(tab==='historial')this.cargarCertificados();if(tab==='responsable_historial')this.cargarCertificadosResponsable();if(tab==='movimientos')this.cargarMovimientos();}
  cargarDashboard(forzar=false){if(this.dashboardCargado&&!forzar)return;this.cargandoDashboard=true;this.api.dashboard(this.proyectoId).subscribe({next:r=>{this.dashboardData=r;this.dashboardCargado=true;this.cargandoDashboard=false;},error:e=>{this.cargandoDashboard=false;this.fallar(e,'No se pudo cargar el dashboard');}});}
  actualizarDashboard(){this.cargarDashboard(true);}
  maximoCurva(){const puntos=this.dashboardData?.curva||[];return Math.max(1,...puntos.flatMap((p:any)=>[Number(p.plan_cliente_acumulado||0),Number(p.real_cliente_acumulado||0),Number(p.plan_responsable_acumulado||0),Number(p.real_responsable_acumulado||0)]));}
  puntosCurva(campo:string){const puntos=this.dashboardData?.curva||[],max=this.maximoCurva();if(!puntos.length)return'';return puntos.map((p:any,i:number)=>`${puntos.length===1?400:45+i*710/(puntos.length-1)},${265-Number(p[campo]||0)*225/max}`).join(' ');}
  mesesEjeX(){const puntos=this.dashboardData?.curva||[],nombres=['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC'];if(!puntos.length)return[];const primera=String(puntos[0].fecha).slice(0,10).split('-').map(Number),ultima=String(puntos[puntos.length-1].fecha).slice(0,10).split('-').map(Number),actual=new Date(primera[0],primera[1]-1,1),fin=new Date(ultima[0],ultima[1]-1,1),salida:string[]=[];while(actual<=fin&&salida.length<120){salida.push(`${nombres[actual.getMonth()]}${actual.getMonth()===0||salida.length===0?` ${String(actual.getFullYear()).slice(-2)}`:''}`);actual.setMonth(actual.getMonth()+1);}return salida;}
  movimientoVacio(){return{tipo:'INGRESO',fecha:this.hoyLocal(),importe:null,descripcion:'',medio_pago:'TRANSFERENCIA',referencia:'',vinculo_tipo:'LIBRE',certificado_cliente_id:null,registro_compra_id:null,certificado_responsable_id:null};}
  cargarMovimientos(forzar=false){if(this.movimientosCargados&&!forzar)return;this.api.movimientos(this.proyectoId).subscribe({next:r=>{this.finanzas=r;this.movimientosCargados=true;},error:e=>this.fallar(e,'No se pudieron cargar los ingresos y egresos')});}
  abrirMovimiento(){this.nuevoMovimiento=this.movimientoVacio();this.errorModal='';this.mostrandoMovimiento=true;}
  cerrarMovimiento(){this.mostrandoMovimiento=false;this.errorModal='';}
  cambiarTipoMovimiento(){this.errorModal='';this.nuevoMovimiento.vinculo_tipo='LIBRE';this.nuevoMovimiento.certificado_cliente_id=null;this.nuevoMovimiento.registro_compra_id=null;this.nuevoMovimiento.certificado_responsable_id=null;}
  registrosPorTipo(){return(this.finanzas?.registros_compra||[]).filter((r:any)=>String(r.tipo||'').trim().toUpperCase()===String(this.nuevoMovimiento.vinculo_tipo||'').trim().toUpperCase());}
  guardarMovimiento(){this.errorModal='';this.procesando=true;this.api.crearMovimiento(this.proyectoId,this.nuevoMovimiento).subscribe({next:r=>{this.mensaje=r.message;this.cerrarMovimiento();this.procesando=false;this.dashboardCargado=false;this.cargarMovimientos(true);if(this.nuevoMovimiento.vinculo_tipo==='CERTIFICADO_CLIENTE')this.cargarCertificados(true);if(this.nuevoMovimiento.vinculo_tipo==='CERTIFICADO_RESPONSABLE')this.cargarCertificadosResponsable(true);},error:e=>this.fallarModal(e,'No se pudo registrar el movimiento')});}
  solicitarAnularMovimiento(m:any){this.anulandoMovimiento=m;this.motivoAnulacionMovimiento='';}
  cancelarAnulacionMovimiento(){this.anulandoMovimiento=null;this.motivoAnulacionMovimiento='';}
  confirmarAnulacionMovimiento(){if(!this.anulandoMovimiento||!this.motivoAnulacionMovimiento.trim())return;const vinculo=String(this.anulandoMovimiento.vinculo_tipo||'');this.procesando=true;this.api.anularMovimiento(this.proyectoId,Number(this.anulandoMovimiento.movimiento_id),this.motivoAnulacionMovimiento).subscribe({next:r=>{this.mensaje=r.message;this.cancelarAnulacionMovimiento();this.procesando=false;this.dashboardCargado=false;this.cargarMovimientos(true);if(vinculo==='CERTIFICADO_CLIENTE')this.cargarCertificados(true);if(vinculo==='CERTIFICADO_RESPONSABLE')this.cargarCertificadosResponsable(true);},error:e=>this.fallar(e,'No se pudo anular el movimiento')});}
  editar(op:any){this.editando={...op,precio_cliente:Number(op.precio_cliente),costo_responsable:Number(op.costo_responsable)};this.motivo='';this.historialEconomia=[];this.api.historialEconomia(op.operacion_id).subscribe(r=>this.historialEconomia=r);}
  cerrarEdicion(){this.editando=null;this.historialEconomia=[];}
  guardarEconomia(){if(!this.editando)return;this.procesando=true;this.api.actualizarEconomia(this.editando.operacion_id,{precio_cliente:this.editando.precio_cliente,costo_responsable:this.editando.costo_responsable,motivo:this.motivo}).subscribe({next:r=>{this.mensaje=r.message;this.procesando=false;this.cerrarEdicion();this.dashboardCargado=false;this.previewData=null;this.previewResponsableData=null;this.cargar();},error:e=>this.fallar(e,'No se pudo guardar')});}
  cambiarCorte(){this.previewData=null;if(this.metodoCorte==='POR_FECHA')this.operacionCorteId=null;}
  generarPreview(){this.procesando=true;this.previewData=null;const corte={metodo_corte:this.metodoCorte,fecha_certificacion:this.fecha,operacion_corte_id:this.metodoCorte==='POR_OPERACION'?this.operacionCorteId:null};this.api.preview(this.proyectoId,corte).subscribe({next:r=>{this.previewData=r;this.procesando=false;},error:e=>this.fallar(e,'No se pudo generar el preview')});}
  recalcular(l:any){const actual=Number(l.porcentaje_actual);l.delta=Math.max(0,actual-Number(l.porcentaje_anterior));l.importe=Number(l.precio_cliente)*l.delta/100;l.modificado_manualmente=actual!==Number(l.porcentaje_sugerido);}
  totalPreview(){return (this.previewData?.lineas||[]).reduce((s:number,l:any)=>s+Number(l.importe||0),0);}
  emitir(){if(!this.previewData)return;this.procesando=true;const payload={metodo_corte:this.metodoCorte,operacion_corte_id:this.metodoCorte==='POR_OPERACION'?this.operacionCorteId:null,fecha_certificacion:this.fecha,observaciones:this.observaciones,lineas:this.previewData.lineas.map((l:any)=>({operacion_id:l.operacion_id,porcentaje_actual:Number(l.porcentaje_actual),motivo_modificacion:l.motivo_modificacion||null,base:l.base}))};this.api.emitir(this.proyectoId,payload).subscribe({next:r=>{this.mensaje=`Certificado #${r.certificado_cliente_id} emitido correctamente`;this.previewData=null;this.observaciones='';this.procesando=false;this.dashboardCargado=false;this.movimientosCargados=false;this.cargarCertificados(true);this.tab='historial';},error:e=>this.fallar(e,'No se pudo emitir el certificado')});}
  operacionesResponsable(){return this.operaciones.filter((op:any)=>Number(op.responsable_id)===Number(this.responsableId));}
  cambiarResponsable(){this.previewResponsableData=null;this.operacionCorteResponsableId=null;}
  cambiarCorteResponsable(){this.previewResponsableData=null;if(this.metodoCorteResponsable==='POR_FECHA')this.operacionCorteResponsableId=null;}
  generarPreviewResponsable(){if(!this.responsableId)return;this.procesando=true;this.previewResponsableData=null;const corte={responsable_id:this.responsableId,metodo_corte:this.metodoCorteResponsable,fecha_certificacion:this.fechaResponsable,operacion_corte_id:this.metodoCorteResponsable==='POR_OPERACION'?this.operacionCorteResponsableId:null};this.api.previewResponsable(this.proyectoId,corte).subscribe({next:r=>{this.previewResponsableData=r;this.procesando=false;},error:e=>this.fallar(e,'No se pudo generar el preview del responsable')});}
  recalcularResponsable(l:any){const actual=Number(l.porcentaje_actual);l.delta=Math.max(0,actual-Number(l.porcentaje_anterior));l.importe=Number(l.costo_responsable)*l.delta/100;l.modificado_manualmente=actual!==Number(l.porcentaje_sugerido);}
  totalPreviewResponsable(){return(this.previewResponsableData?.lineas||[]).reduce((s:number,l:any)=>s+Number(l.importe||0),0);}
  emitirResponsable(){if(!this.previewResponsableData||!this.responsableId)return;this.procesando=true;const payload={responsable_id:this.responsableId,metodo_corte:this.metodoCorteResponsable,operacion_corte_id:this.metodoCorteResponsable==='POR_OPERACION'?this.operacionCorteResponsableId:null,fecha_certificacion:this.fechaResponsable,observaciones:this.observacionesResponsable,lineas:this.previewResponsableData.lineas.map((l:any)=>({operacion_id:l.operacion_id,porcentaje_actual:Number(l.porcentaje_actual),motivo_modificacion:l.motivo_modificacion||null,base:l.base}))};this.api.emitirResponsable(this.proyectoId,payload).subscribe({next:r=>{this.mensaje=`Certificado a responsable #${r.certificado_responsable_id} emitido correctamente`;this.previewResponsableData=null;this.observacionesResponsable='';this.procesando=false;this.dashboardCargado=false;this.movimientosCargados=false;this.cargarCertificadosResponsable(true);this.tab='responsable_historial';},error:e=>this.fallar(e,'No se pudo emitir el certificado a responsable')});}
  abrirCertificadoResponsable(id:number){this.api.certificadoResponsable(this.proyectoId,id).subscribe({next:r=>this.detalleResponsable=r,error:e=>this.fallar(e,'No se pudo abrir el certificado a responsable')});}
  descargarPdfResponsable(id:number,event?:Event){event?.stopPropagation();this.procesando=true;this.api.pdfCertificadoResponsable(this.proyectoId,id).subscribe({next:archivo=>{this.guardarArchivo(archivo,`certificado-responsable-${id}.pdf`);this.procesando=false;},error:e=>this.fallar(e,'No se pudo generar el PDF del certificado a responsable')});}
  solicitarEliminarCertificadoResponsable(certificado:any,event?:Event){event?.stopPropagation();if(!certificado?.es_ultimo_emitido)return;this.eliminandoCertificadoResponsable=certificado;this.motivoEliminacionResponsable='';}
  cancelarEliminacionResponsable(){this.eliminandoCertificadoResponsable=null;this.motivoEliminacionResponsable='';}
  confirmarEliminacionResponsable(){if(!this.eliminandoCertificadoResponsable||!this.motivoEliminacionResponsable.trim())return;this.procesando=true;const id=Number(this.eliminandoCertificadoResponsable.certificado_responsable_id);this.api.eliminarCertificadoResponsable(this.proyectoId,id,this.motivoEliminacionResponsable).subscribe({next:r=>{const anterior=r.certificado_anterior_vigente?.certificado_responsable_id;this.mensaje=`Certificado a responsable #${id} eliminado. ${anterior?`El proximo delta parte del #${anterior}`:'No queda un certificado anterior vigente para ese responsable'}`;this.detalleResponsable=null;this.previewResponsableData=null;this.cancelarEliminacionResponsable();this.procesando=false;this.dashboardCargado=false;this.movimientosCargados=false;this.cargar();this.cargarCertificadosResponsable(true);this.tab='responsable_historial';},error:e=>{this.cancelarEliminacionResponsable();this.detalleResponsable=null;this.error=e?.error?.message||'No se pudo eliminar el certificado a responsable';this.procesando=false;this.cargarCertificadosResponsable(true);}});}
  seleccionarCsv(event:Event){const input=event.target as HTMLInputElement;const archivo=input.files?.[0];input.value='';if(!archivo)return;if(!archivo.name.toLowerCase().endsWith('.csv')){this.error='Seleccione un archivo con extensión .csv';return;}const lector=new FileReader();lector.onload=()=>{this.nombreArchivo=archivo.name;this.contenidoCsv=String(lector.result||'');this.procesando=true;this.api.previewImportacion(this.proyectoId,this.contenidoCsv).subscribe({next:r=>{this.importacion=r;this.procesando=false;},error:e=>this.fallar(e,'No se pudo validar el CSV')});};lector.onerror=()=>this.fallar(null,'No se pudo leer el archivo');lector.readAsText(archivo,'UTF-8');}
  cerrarImportacion(){this.importacion=null;this.contenidoCsv='';this.nombreArchivo='';}
  confirmarImportacion(){if(!this.importacion||this.importacion.filas_con_error)return;this.procesando=true;this.api.importarCostos(this.proyectoId,this.contenidoCsv).subscribe({next:r=>{this.mensaje=`${r.message}. Operaciones actualizadas: ${r.operaciones_actualizadas}`;this.cerrarImportacion();this.previewData=null;this.previewResponsableData=null;this.dashboardCargado=false;this.procesando=false;this.cargar();},error:e=>this.fallar(e,'No se pudo importar el CSV')});}
  abrirCertificado(id:number){this.api.certificado(this.proyectoId,id).subscribe({next:r=>this.detalle=r,error:e=>this.fallar(e,'No se pudo abrir el certificado')});}
  descargarPdf(id:number,event?:Event){event?.stopPropagation();this.procesando=true;this.api.pdfCertificado(this.proyectoId,id).subscribe({next:archivo=>{this.guardarArchivo(archivo,`certificado-cliente-${id}.pdf`);this.procesando=false;},error:e=>this.fallar(e,'No se pudo generar el PDF del certificado')});}
  private guardarArchivo(archivo:Blob,nombre:string){const url=URL.createObjectURL(archivo),enlace=document.createElement('a');enlace.href=url;enlace.download=nombre;document.body.appendChild(enlace);enlace.click();enlace.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  solicitarEliminarCertificado(){if(!this.detalle?.certificado?.es_ultimo_emitido)return;this.eliminandoCertificado=this.detalle.certificado;this.motivoEliminacion='';}
  solicitarEliminarDesdeCard(certificado:any,event:Event){event.stopPropagation();if(!certificado?.es_ultimo_emitido)return;this.eliminandoCertificado=certificado;this.motivoEliminacion='';}
  cancelarEliminacion(){this.eliminandoCertificado=null;this.motivoEliminacion='';}
  confirmarEliminacion(){if(!this.eliminandoCertificado||!this.motivoEliminacion.trim())return;this.procesando=true;const id=Number(this.eliminandoCertificado.certificado_cliente_id);this.api.eliminarCertificado(this.proyectoId,id,this.motivoEliminacion).subscribe({next:r=>{const anterior=r.certificado_anterior_vigente?.certificado_cliente_id;this.mensaje=`Certificado #${id} eliminado. ${anterior?`Los próximos deltas parten del certificado #${anterior}`:'No queda un certificado anterior vigente'}`;this.detalle=null;this.previewData=null;this.cancelarEliminacion();this.procesando=false;this.dashboardCargado=false;this.movimientosCargados=false;this.cargar();this.cargarCertificados(true);this.tab='historial';},error:e=>{this.cancelarEliminacion();this.detalle=null;this.error=e?.error?.message||'No se pudo eliminar el certificado';this.procesando=false;this.cargarCertificados(true);}});}
  fallar(e:any,fallback:string){this.error=e?.error?.message||fallback;this.procesando=false;this.cargando=false;}
  fallarModal(e:any,fallback:string){this.errorModal=e?.error?.message||fallback;this.procesando=false;}
}
