const test=require('node:test');const assert=require('node:assert/strict');const {calcularLinea}=require('../services/reglasCostos');
const {lineaPreview,calcularDetalleEmision,compararBase,validarProyecto,validarObservaciones,validarMotivoEliminacion,validarCertificadoEliminable,normalizarCorte,seleccionarOperaciones,calcularAvanceEtapas}=require('../services/CertificacionCliente.service');
const {parsearCsv,armarPreview}=require('../services/ImportacionCostos.service');
const {validarMovimiento}=require('../services/MovimientoFinanciero.service');
const responsable=require('../services/CertificacionResponsable.service');
test('primera certificacion calcula el delta completo',()=>assert.deepEqual(calcularLinea({avance:40,anterior:0,actual:40,precio:1000}),{avance:40,anterior:0,actual:40,precio:1000,delta:40,importe:400,manual:false,motivo:null}));
test('certificado posterior cobra solo el delta',()=>assert.equal(calcularLinea({avance:70,anterior:40,actual:70,precio:1500}).importe,450));
test('precio cero es valido',()=>assert.equal(calcularLinea({avance:25,anterior:0,actual:25,precio:0}).importe,0));
test('permite certificar menos que avance con motivo',()=>assert.equal(calcularLinea({avance:60,anterior:30,actual:50,precio:1000,motivo:'Acuerdo de obra'}).delta,20));
test('rechaza modificacion sin motivo',()=>assert.throws(()=>calcularLinea({avance:60,anterior:30,actual:50,precio:1000}),/requiere motivo/));
test('rechaza retroceso respecto al certificado anterior',()=>assert.throws(()=>calcularLinea({avance:80,anterior:60,actual:50,precio:1000,motivo:'x'}),/entre el anterior/));
test('rechaza porcentaje superior a 100',()=>assert.throws(()=>calcularLinea({avance:80,anterior:60,actual:101,precio:1000,motivo:'x'}),/entre el anterior/));
test('el precio nuevo solo valoriza el delta futuro',()=>{assert.equal(calcularLinea({avance:40,anterior:0,actual:40,precio:1000}).importe,400);assert.equal(calcularLinea({avance:70,anterior:40,actual:70,precio:1500}).importe,450);});
test('segundo preview respeta el acumulado anterior sin exigir motivo',()=>{const linea=lineaPreview({avance_fisico_referencia:0,porcentaje_anterior:20,precio_cliente:15000,economia_version:'0x1'});assert.equal(linea.porcentaje_sugerido,20);assert.equal(linea.delta,0);assert.equal(linea.importe,0);});
test('emision posterior conserva acumulado anterior sin tratarlo como cambio manual',()=>{const linea=calcularDetalleEmision({avance_fisico_referencia:0,porcentaje_anterior:20,precio_cliente:15000},{porcentaje_actual:20});assert.equal(linea.manual,false);assert.equal(linea.delta,0);assert.equal(linea.avance,0);});
test('preview obsoleto detecta cambio de precio por rowversion',()=>{const op={avance_fisico_referencia:20,porcentaje_anterior:0,precio_cliente:1000,economia_version:'0x02',avance_id:1,detalle_anterior_id:null};const base={economia_version:'0x01',avance_id:1,detalle_anterior_id:null,avance_fisico_referencia:20,porcentaje_anterior:0};assert.equal(compararBase(op,base),false);});
test('preview obsoleto detecta un nuevo certificado anterior',()=>{const op={avance_fisico_referencia:20,porcentaje_anterior:10,precio_cliente:1000,economia_version:'0x01',avance_id:1,detalle_anterior_id:5};const base={economia_version:'0x01',avance_id:1,detalle_anterior_id:null,avance_fisico_referencia:20,porcentaje_anterior:0};assert.equal(compararBase(op,base),false);});
test('rechaza proyecto inactivo',()=>assert.throws(()=>validarProyecto({activo:false,eliminado:false,estado:'PAUSADO',cliente_id:1}),/activo/));
test('rechaza proyecto activo sin cliente',()=>assert.throws(()=>validarProyecto({activo:true,eliminado:false,estado:'ACTIVO',cliente_id:null}),/cliente/));
test('acepta observaciones de exactamente 1000 caracteres',()=>assert.equal(validarObservaciones('x'.repeat(1000)).length,1000));
test('rechaza observaciones mayores a 1000 caracteres',()=>assert.throws(()=>validarObservaciones('x'.repeat(1001)),/1000/));
test('rechaza motivos mayores a 500 caracteres',()=>assert.throws(()=>calcularLinea({avance:0,anterior:0,actual:10,precio:100,motivo:'x'.repeat(501)}),/500/));
test('normaliza el corte por fecha sin operacion',()=>assert.deepEqual(normalizarCorte({metodo_corte:'POR_FECHA',fecha_certificacion:'2026-08-24',operacion_corte_id:99}),{metodo_corte:'POR_FECHA',fecha_certificacion:'2026-08-24',operacion_corte_id:null}));
test('corte por operacion exige una operacion',()=>assert.throws(()=>normalizarCorte({metodo_corte:'POR_OPERACION',fecha_certificacion:'2026-08-24'}),/seleccionar/));
test('corte por fecha incluye solo operaciones cuyo inicio vigente ingreso al corte',()=>{const rs=[[],[
  {operacion_id:1,proyecto_id:8,secuencia:100,nombre:'A',fecha_inicio_estimada:'2026-08-20',fecha_fin_estimada:'2026-08-21'},
  {operacion_id:2,proyecto_id:8,secuencia:200,nombre:'B',fecha_inicio_estimada:'2026-08-25',fecha_fin_estimada:'2026-08-26'}
],[],[],[]];const seleccion=seleccionarOperaciones(rs,{metodo_corte:'POR_FECHA',fecha_certificacion:'2026-08-24'});assert.deepEqual(seleccion.operaciones.map(x=>x.operacion_id),[1]);});
test('corte por operacion incluye la seleccionada y todas las secuencias anteriores',()=>{const rs=[[],[
  {operacion_id:1,proyecto_id:8,secuencia:100,nombre:'A',fecha_inicio_estimada:'2026-08-20',fecha_fin_estimada:'2026-08-21'},
  {operacion_id:2,proyecto_id:8,secuencia:200,nombre:'B',fecha_inicio_estimada:'2026-08-25',fecha_fin_estimada:'2026-08-26'},
  {operacion_id:3,proyecto_id:8,secuencia:300,nombre:'C',fecha_inicio_estimada:'2026-08-27',fecha_fin_estimada:'2026-08-28'}
],[],[],[]];const seleccion=seleccionarOperaciones(rs,{metodo_corte:'POR_OPERACION',fecha_certificacion:'2026-08-24',operacion_corte_id:2});assert.deepEqual(seleccion.operaciones.map(x=>x.operacion_id),[1,2]);assert.equal(seleccion.operacion_corte.secuencia,200);});
test('CSV acepta cabeceras definitivas y punto decimal',()=>assert.deepEqual(parsearCsv('secuencia,precio_cliente,costo_responsable\n100,1500.25,900')[0],{fila:2,secuencia:100,precio_cliente:1500.25,costo_responsable:900,errores:[]}));
test('CSV con punto y coma acepta coma decimal',()=>assert.equal(parsearCsv('secuencia;precio_cliente;costo_responsable\n100;1500,25;900,5')[0].precio_cliente,1500.25));
test('CSV ampliado acepta cronograma y numero planificado',()=>{const fila=parsearCsv('secuencia,precio_cliente,costo_responsable,cronograma_certificacion,nro_certificado_planificado\n100,1500,600,2026-09-15,1')[0];assert.equal(fila.cronograma_certificacion,'2026-09-15');assert.equal(fila.nro_certificado_planificado,1);assert.equal(fila.incluye_cronograma,true);});
test('CSV ampliado permite vaciar la planificacion',()=>{const fila=parsearCsv('secuencia,precio_cliente,costo_responsable,cronograma_certificacion,nro_certificado_planificado\n100,1500,600,,')[0];assert.equal(fila.cronograma_certificacion,null);assert.equal(fila.nro_certificado_planificado,null);assert.equal(fila.errores.length,0);});
test('CSV ampliado rechaza fecha inexistente o numero sin fecha',()=>{const filas=parsearCsv('secuencia,precio_cliente,costo_responsable,cronograma_certificacion,nro_certificado_planificado\n100,1500,600,2026-02-31,1\n200,2000,1000,,2');assert.match(filas[0].errores.join(' '),/Cronograma/);assert.match(filas[1].errores.join(' '),/Cronograma/);});
test('CSV rechaza cabeceras distintas',()=>assert.throws(()=>parsearCsv('operacion,precio,costo\n100,1,1'),/cabeceras/));
test('preview CSV informa nombre, etapa, cambios y secuencias repetidas',()=>{const filas=parsearCsv('secuencia,precio_cliente,costo_responsable\n100,120,80\n100,130,90');const preview=armarPreview(filas,[{operacion_id:9,secuencia:100,nombre:'Montaje',etapa_nombre:'Obra',precio_cliente:100,costo_responsable:80}]);assert.equal(preview.filas[0].operacion_nombre,'Montaje');assert.equal(preview.filas_con_error,2);assert.match(preview.filas[0].errores[0],/repetida/);});
test('preview CSV reemplaza el valor anterior sin sumarlo ni concatenarlo',()=>{const filas=parsearCsv('secuencia,precio_cliente,costo_responsable\n100,10000,10000');const preview=armarPreview(filas,[{operacion_id:9,secuencia:100,nombre:'Montaje',etapa_nombre:'Obra',precio_cliente:15000,costo_responsable:6000}]);assert.equal(preview.filas_con_error,0);assert.equal(preview.filas[0].precio_cliente,10000);assert.equal(preview.filas[0].costo_responsable,10000);assert.equal(preview.filas[0].cambia,true);});
test('preview CSV bloquea un salto compatible con concatenacion accidental',()=>{const filas=parsearCsv('secuencia,precio_cliente,costo_responsable\n100,150010000,60010000');const preview=armarPreview(filas,[{operacion_id:9,secuencia:100,nombre:'Montaje',etapa_nombre:'Obra',precio_cliente:15000,costo_responsable:6000}]);assert.equal(preview.filas_con_error,1);assert.match(preview.filas[0].errores.join(' '),/posible concatenacion/);});
test('preview conserva cronograma cuando usa CSV anterior de tres columnas',()=>{const filas=parsearCsv('secuencia,precio_cliente,costo_responsable\n100,1500,600');const preview=armarPreview(filas,[{operacion_id:9,secuencia:100,nombre:'Montaje',etapa_nombre:'Obra',precio_cliente:1500,costo_responsable:600,cronograma_certificacion_fecha:'2026-09-15',numero_certificado_planificado:1}]);assert.equal(preview.filas[0].cambia_cronograma,false);assert.equal(preview.filas[0].cronograma_certificacion_anterior,'2026-09-15');});
test('preview rechaza un mismo certificado planificado con fechas diferentes',()=>{const filas=parsearCsv('secuencia,precio_cliente,costo_responsable,cronograma_certificacion,nro_certificado_planificado\n100,1500,600,2026-09-15,1\n200,2000,1000,2026-10-15,1');const operaciones=[{operacion_id:9,secuencia:100,nombre:'A',etapa_nombre:'E',precio_cliente:1500,costo_responsable:600},{operacion_id:10,secuencia:200,nombre:'B',etapa_nombre:'E',precio_cliente:2000,costo_responsable:1000}];const preview=armarPreview(filas,operaciones);assert.equal(preview.filas_con_error,2);assert.match(preview.filas[0].errores.join(' '),/fechas diferentes/);});
test('el motivo es obligatorio para eliminar un certificado',()=>assert.throws(()=>validarMotivoEliminacion('  '),/obligatorio/));
test('rechaza eliminar un certificado que no es el ultimo emitido',()=>assert.throws(()=>validarCertificadoEliminable({certificado_cliente_id:2,estado:'EMITIDO'},{certificado_cliente_id:3},2),/ultimo/));
test('permite eliminar el ultimo certificado emitido',()=>assert.equal(validarCertificadoEliminable({certificado_cliente_id:3,estado:'EMITIDO'},{certificado_cliente_id:3},3).certificado_cliente_id,3));
test('certificado resume el avance de etapa ponderado por el peso de sus operaciones',()=>{const etapas=calcularAvanceEtapas([
  {etapa_id:1,etapa_nombre:'Etapa 1',etapa_orden:1,porcentaje_actual:100,peso_operacion:40},
  {etapa_id:1,etapa_nombre:'Etapa 1',etapa_orden:1,porcentaje_actual:50,peso_operacion:60},
  {etapa_id:2,etapa_nombre:'Etapa 2',etapa_orden:2,porcentaje_actual:50,peso_operacion:100}
]);assert.deepEqual(etapas.map(e=>[e.etapa_nombre,e.porcentaje_certificado]),[['Etapa 1',70],['Etapa 2',50]]);});
test('ingreso permite vinculo libre o certificado a cliente',()=>{assert.equal(validarMovimiento({tipo:'INGRESO',vinculo_tipo:'LIBRE',fecha:'2026-08-25',importe:100,descripcion:'Anticipo'}).vinculo_tipo,'LIBRE');assert.equal(validarMovimiento({tipo:'INGRESO',vinculo_tipo:'CERTIFICADO_CLIENTE',certificado_cliente_id:4,fecha:'2026-08-25',importe:100,descripcion:'Cobro'}).certificado_cliente_id,4);});
test('egreso permite OC y rechaza certificado a cliente',()=>{assert.equal(validarMovimiento({tipo:'EGRESO',vinculo_tipo:'OC',registro_compra_id:2,fecha:'2026-08-25',importe:80,descripcion:'Compra'}).registro_compra_id,2);assert.throws(()=>validarMovimiento({tipo:'EGRESO',vinculo_tipo:'CERTIFICADO_CLIENTE',certificado_cliente_id:4,fecha:'2026-08-25',importe:80,descripcion:'Invalido'}),/no corresponde/);});
test('movimiento exige importe positivo y descripcion',()=>{assert.throws(()=>validarMovimiento({tipo:'INGRESO',fecha:'2026-08-25',importe:0,descripcion:'x'}),/Importe/);assert.throws(()=>validarMovimiento({tipo:'INGRESO',fecha:'2026-08-25',importe:1}),/descripcion/);});
test('certificado a responsable exige responsable seleccionado',()=>assert.throws(()=>responsable.normalizarOpciones({metodo_corte:'POR_FECHA',fecha_certificacion:'2026-08-25'}),/responsable/));
test('preview de responsable valoriza con costo y no con precio cliente',()=>{const linea=responsable.lineaPreview({responsable_id:4,avance_fisico_referencia:50,porcentaje_anterior:20,costo_responsable:800,precio_cliente:5000,economia_version:'0x01'});assert.equal(linea.delta,30);assert.equal(linea.importe,240);assert.equal(linea.costo_responsable,800);});
test('segundo certificado a responsable usa solamente el delta',()=>{const detalle=responsable.calcularDetalleEmision({avance_fisico_referencia:70,porcentaje_anterior:40,costo_responsable:1000},{porcentaje_actual:70});assert.equal(detalle.delta,30);assert.equal(detalle.importe,300);});
test('preview responsable queda obsoleto si cambia el responsable',()=>{const op={responsable_id:5,avance_fisico_referencia:20,porcentaje_anterior:0,costo_responsable:1000,economia_version:'0x01'};const base=responsable.lineaPreview(op).base;base.responsable_id=6;assert.equal(responsable.compararBase(op,base),false);});
test('egreso permite vincular certificado a responsable',()=>{const dato=validarMovimiento({tipo:'EGRESO',vinculo_tipo:'CERTIFICADO_RESPONSABLE',certificado_responsable_id:7,fecha:'2026-08-25',importe:100,descripcion:'Pago contratista'});assert.equal(dato.certificado_responsable_id,7);assert.equal(dato.tipo,'EGRESO');});
